/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import static java.util.stream.IntStream.builder;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.xml.sax.InputSource;

/**
 *
 * @author USER
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    private Connection conn;
    private Statement stat;
    private ResultSet rs;
    private DefaultTableModel model;
    private DefaultTableModel model2;
    private DefaultTableModel model3;
    private DefaultTableModel model4;
    private DefaultTableModel model5;





    //
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    
    public MainAdmin(String kirim) {
        initComponents();
        conn = Koneksi.koneksi();
        //
        tf_id.setText(kirim);
       //warna
        warna();
        //tampil gambar
        tampilgambar();
        //
        //tabel pinjam
        model = new DefaultTableModel();
        model.addColumn("No");        
        model.addColumn("No Buku");
        model.addColumn("ID User");
        model.addColumn("Nama");
        model.addColumn("Buku");
        model.addColumn("Dipinjam");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kmbl");
        model.addColumn("Total  Hari");

    tabelPinjam.setModel(model);
    tabel_pinjam.setModel(model);
    getDataPinjam();
        
        //tabel buku
        model2 = new DefaultTableModel();
        model2.addColumn("No");
        model2.addColumn("Nama");
        model2.addColumn("Penulis");
        model2.addColumn("Stok");
    Tabelbuku.setModel(model2);
    tabel_buku.setModel(model2);
    getDataBuku();
    
    
    //tabel anggota
        model3 = new DefaultTableModel();
        model3.addColumn("ID");
        model3.addColumn("Nama");
        tabelAnggota.setModel(model3);
    getDataAnggota();
    
    //tabel anggota 2
        model4 = new DefaultTableModel();
        model4.addColumn("ID");
        model4.addColumn("Nama");
        model4.addColumn("Email");
        model4.addColumn("Password");
        tabel_anggota.setModel(model4);
    getDataAnggota2();
    
    //tabel kembali
        model5 = new DefaultTableModel();
        model5.addColumn("No");        
        model5.addColumn("No Buku");
        model5.addColumn("ID User");
        model5.addColumn("Nama");
        model5.addColumn("Buku");
        model5.addColumn("Dipinjam");
        model5.addColumn("Tgl Pinjam");
        model5.addColumn("Tgl Kmbl");

    tabel_kembali.setModel(model5);
    getDataKembali();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        btnLibrary = new javax.swing.JLabel();
        btnArticle = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kananpane = new javax.swing.JPanel();
        profilepane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_path = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        btn_pilihgambar = new javax.swing.JButton();
        tf_kodee = new javax.swing.JTextField();
        tf_tampil = new javax.swing.JLabel();
        tf_id = new javax.swing.JLabel();
        gambar_User = new javax.swing.JLabel();
        gambarprofile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        librarypane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tf_jmlhBuku = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        tglkmbl = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        tf_tglPinjam = new javax.swing.JTextField();
        tf_ttlhari = new javax.swing.JTextField();
        tf_tglkmbl = new javax.swing.JTextField();
        tf_idUser = new javax.swing.JTextField();
        tf_stokbuku = new javax.swing.JTextField();
        tf_bukuuser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPinjam = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabelbuku = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_namaUser = new javax.swing.JTextField();
        btn_pilihgambar1 = new javax.swing.JButton();
        tf_idBuku = new javax.swing.JTextField();
        tf_namaBuku = new javax.swing.JTextField();
        tf_penulis = new javax.swing.JTextField();
        lbl_gambarbuku = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_pinjamUbah = new javax.swing.JButton();
        btn_segarkan = new javax.swing.JButton();
        btn_tambahbuku = new javax.swing.JButton();
        btn_ubahbuku = new javax.swing.JButton();
        btn_hapuspinjam = new javax.swing.JButton();
        lbl_nobuku = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        lbl_nopinjam = new javax.swing.JLabel();
        cb_enabletf = new javax.swing.JCheckBox();
        btn_hapus1 = new javax.swing.JButton();
        btn_hapus2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reportpane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_kembali = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabel_pinjam = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabel_anggota = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabel_buku = new javax.swing.JTable();
        pinjam = new javax.swing.JButton();
        cetak_pinjam = new javax.swing.JButton();
        buku = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        cetak_kembali = new javax.swing.JButton();
        anggota = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_cetakkembali = new javax.swing.JTextField();
        tf_cetakpinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aboutpane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPane.setBackground(new java.awt.Color(255, 255, 255));

        kiri.setBackground(new java.awt.Color(204, 255, 255));
        kiri.setPreferredSize(new java.awt.Dimension(233, 600));
        kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(1, 193, 198));
        btnProfile.setText("I");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
        });
        kiri.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 208, 223, 40));

        btnLibrary.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLibrary.setForeground(new java.awt.Color(1, 193, 198));
        btnLibrary.setText("I");
        btnLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibraryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibraryMouseExited(evt);
            }
        });
        kiri.add(btnLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 272, 223, 40));

        btnArticle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnArticle.setForeground(new java.awt.Color(1, 193, 198));
        btnArticle.setText("I");
        btnArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticleMouseExited(evt);
            }
        });
        kiri.add(btnArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 334, 223, 40));

        btnAbout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(1, 193, 198));
        btnAbout.setText("I");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        kiri.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 398, 223, 40));

        btnLogout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(1, 193, 198));
        btnLogout.setText("I");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        kiri.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 503, 223, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kiri2.jpg"))); // NOI18N
        kiri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kananpane.setPreferredSize(new java.awt.Dimension(764, 600));
        kananpane.setLayout(new java.awt.CardLayout());

        profilepane.setBackground(new java.awt.Color(255, 255, 255));
        profilepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_path.setText("-");
        jPanel1.add(lbl_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 181, 20));

        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 150, 110, 30));

        btn_pilihgambar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pilihgambar.setText("Pilih gambar");
        btn_pilihgambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihgambarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pilihgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 100, 110, 30));

        tf_kodee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_kodee.setForeground(new java.awt.Color(0, 204, 204));
        tf_kodee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_kodee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel1.add(tf_kodee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 190, 40));

        profilepane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 730, 240));

        tf_tampil.setText("tf_tampil");
        profilepane.add(tf_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        tf_id.setText("tf_id");
        profilepane.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));
        profilepane.add(gambar_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 170, 178, 156));

        gambarprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/profile2.jpg"))); // NOI18N
        profilepane.add(gambarprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MainAdmin.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        profilepane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, -1));

        kananpane.add(profilepane, "card2");

        librarypane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelAnggota);

        librarypane.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 357, 140, 210));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Library");
        librarypane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        tf_jmlhBuku.setEditable(false);
        tf_jmlhBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_jmlhBuku.setForeground(new java.awt.Color(0, 153, 153));
        tf_jmlhBuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_jmlhBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_jmlhBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jmlhBukuKeyTyped(evt);
            }
        });
        librarypane.add(tf_jmlhBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 60, 30));

        tglpinjam.setBackground(new java.awt.Color(255, 255, 255));
        tglpinjam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglpinjam.setForeground(new java.awt.Color(255, 255, 255));
        tglpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tglpinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglpinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tglpinjamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tglpinjamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tglpinjamMouseReleased(evt);
            }
        });
        tglpinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tglpinjamKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tglpinjamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tglpinjamKeyTyped(evt);
            }
        });
        librarypane.add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 520, 40, 30));

        tglkmbl.setBackground(new java.awt.Color(255, 255, 255));
        tglkmbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglkmbl.setForeground(new java.awt.Color(255, 255, 255));
        tglkmbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglkmblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tglkmblMouseExited(evt);
            }
        });
        librarypane.add(tglkmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 560, 40, 30));

        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        librarypane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 200, 80));

        tf_tglPinjam.setEditable(false);
        tf_tglPinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_tglPinjam.setForeground(new java.awt.Color(0, 153, 153));
        tf_tglPinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tglPinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_tglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tglPinjamActionPerformed(evt);
            }
        });
        librarypane.add(tf_tglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 140, 30));

        tf_ttlhari.setEditable(false);
        tf_ttlhari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_ttlhari.setForeground(new java.awt.Color(0, 153, 153));
        tf_ttlhari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_ttlhari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_ttlhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ttlhariActionPerformed(evt);
            }
        });
        librarypane.add(tf_ttlhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 60, 30));

        tf_tglkmbl.setEditable(false);
        tf_tglkmbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_tglkmbl.setForeground(new java.awt.Color(0, 153, 153));
        tf_tglkmbl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tglkmbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_tglkmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 140, 30));

        tf_idUser.setEditable(false);
        tf_idUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_idUser.setForeground(new java.awt.Color(0, 153, 153));
        tf_idUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_idUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_idUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_idUserKeyTyped(evt);
            }
        });
        librarypane.add(tf_idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 100, 30));

        tf_stokbuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_stokbuku.setForeground(new java.awt.Color(0, 153, 153));
        tf_stokbuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_stokbuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_stokbuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_stokbukuKeyTyped(evt);
            }
        });
        librarypane.add(tf_stokbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 70, 30));

        tf_bukuuser.setEditable(false);
        tf_bukuuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_bukuuser.setForeground(new java.awt.Color(0, 153, 153));
        tf_bukuuser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_bukuuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_bukuuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 170, 30));

        tabelPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPinjam);

        librarypane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 460, 160));

        Tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelbukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabelbuku);

        librarypane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 270, 160));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID User");
        librarypane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama");
        librarypane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buku");
        librarypane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tgl Kembali");
        librarypane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah Buku");
        librarypane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total Hari");
        librarypane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tgl Pinjam");
        librarypane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID Buku");
        librarypane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nama");
        librarypane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Penulis");
        librarypane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Stok Buku");
        librarypane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Gambar");
        librarypane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        tf_namaUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_namaUser.setForeground(new java.awt.Color(0, 153, 153));
        tf_namaUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_namaUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 170, 30));

        btn_pilihgambar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pilihgambar1.setText("Pilih");
        btn_pilihgambar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihgambar1ActionPerformed(evt);
            }
        });
        librarypane.add(btn_pilihgambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 60, 30));

        tf_idBuku.setEditable(false);
        tf_idBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_idBuku.setForeground(new java.awt.Color(0, 153, 153));
        tf_idBuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_idBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_idBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 80, 30));

        tf_namaBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_namaBuku.setForeground(new java.awt.Color(0, 153, 153));
        tf_namaBuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_namaBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_namaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 160, 30));

        tf_penulis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_penulis.setForeground(new java.awt.Color(0, 153, 153));
        tf_penulis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_penulis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        librarypane.add(tf_penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 160, 30));

        lbl_gambarbuku.setBackground(new java.awt.Color(255, 255, 255));
        librarypane.add(lbl_gambarbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 100, 75));

        btn_tambah.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        librarypane.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btn_pinjamUbah.setBackground(new java.awt.Color(255, 255, 255));
        btn_pinjamUbah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_pinjamUbah.setText("Ubah");
        btn_pinjamUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pinjamUbahActionPerformed(evt);
            }
        });
        librarypane.add(btn_pinjamUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, -1));

        btn_segarkan.setBackground(new java.awt.Color(255, 255, 255));
        btn_segarkan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_segarkan.setText("Refresh");
        btn_segarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_segarkanActionPerformed(evt);
            }
        });
        librarypane.add(btn_segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, -1));

        btn_tambahbuku.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambahbuku.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_tambahbuku.setText("Tambah");
        btn_tambahbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahbukuActionPerformed(evt);
            }
        });
        librarypane.add(btn_tambahbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        btn_ubahbuku.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubahbuku.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_ubahbuku.setText("Ubah");
        btn_ubahbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahbukuActionPerformed(evt);
            }
        });
        librarypane.add(btn_ubahbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 70, -1));

        btn_hapuspinjam.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapuspinjam.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_hapuspinjam.setText("Hapus");
        btn_hapuspinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapuspinjamActionPerformed(evt);
            }
        });
        librarypane.add(btn_hapuspinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 120, 70, -1));

        lbl_nobuku.setText("no_Buku");
        librarypane.add(lbl_nobuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        tfCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfCari.setForeground(new java.awt.Color(51, 51, 51));
        tfCari.setText("Cari");
        tfCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfCariMouseClicked(evt);
            }
        });
        tfCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariKeyReleased(evt);
            }
        });
        librarypane.add(tfCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 140, 30));

        lbl_nopinjam.setText("no_pinjam");
        librarypane.add(lbl_nopinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        cb_enabletf.setBackground(new java.awt.Color(255, 255, 255));
        cb_enabletf.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cb_enabletf.setText("aktifkan Edit");
        cb_enabletf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_enabletfActionPerformed(evt);
            }
        });
        librarypane.add(cb_enabletf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, -1));

        btn_hapus1.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_hapus1.setText("Hapus");
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });
        librarypane.add(btn_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 120, 70, -1));

        btn_hapus2.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_hapus2.setText("Hapus");
        btn_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus2ActionPerformed(evt);
            }
        });
        librarypane.add(btn_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/library.jpg"))); // NOI18N
        librarypane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(librarypane, "card3");

        reportpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Report");
        reportpane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        tabel_kembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kembaliMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_kembali);

        reportpane.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 160));

        tabel_pinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pinjamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabel_pinjam);

        reportpane.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 160));

        tabel_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabel_anggota);

        reportpane.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 280, 160));

        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabel_buku);

        reportpane.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 280, 160));

        pinjam.setBackground(new java.awt.Color(255, 255, 255));
        pinjam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        pinjam.setText("Cetak PerData");
        pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamActionPerformed(evt);
            }
        });
        reportpane.add(pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, 30));

        cetak_pinjam.setBackground(new java.awt.Color(255, 255, 255));
        cetak_pinjam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cetak_pinjam.setText("Cetak");
        cetak_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_pinjamActionPerformed(evt);
            }
        });
        reportpane.add(cetak_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 310, 80, 30));

        buku.setBackground(new java.awt.Color(255, 255, 255));
        buku.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        buku.setText("Cetak");
        buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuActionPerformed(evt);
            }
        });
        reportpane.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 80, 30));

        kembali.setBackground(new java.awt.Color(255, 255, 255));
        kembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kembali.setText("CetakPerData");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        reportpane.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 130, 30));

        cetak_kembali.setBackground(new java.awt.Color(255, 255, 255));
        cetak_kembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cetak_kembali.setText("Cetak");
        cetak_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_kembaliActionPerformed(evt);
            }
        });
        reportpane.add(cetak_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 80, 30));

        anggota.setBackground(new java.awt.Color(255, 255, 255));
        anggota.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        anggota.setText("Cetak");
        anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaActionPerformed(evt);
            }
        });
        reportpane.add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 80, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tabel Buku");
        reportpane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tabel Pinjam");
        reportpane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tabel Kembali");
        reportpane.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tabel Anggota");
        reportpane.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        tf_cetakkembali.setBorder(null);
        reportpane.add(tf_cetakkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 50, 30));

        tf_cetakpinjam.setBorder(null);
        reportpane.add(tf_cetakpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/library.jpg"))); // NOI18N
        reportpane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(reportpane, "card4");

        aboutpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/About.jpg"))); // NOI18N
        aboutpane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(aboutpane, "card5");

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addComponent(kiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kananpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kananpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(MainPane, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(profilepane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        // TODO add your handling code here:
        btnProfile.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        // TODO add your handling code here:
        btnProfile.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProfileMouseExited

    private void btnLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(librarypane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnLibraryMouseClicked

    private void btnLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseEntered
        // TODO add your handling code here:
        btnLibrary.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnLibraryMouseEntered

    private void btnLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseExited
        // TODO add your handling code here:
        btnLibrary.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLibraryMouseExited

    private void btnArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(reportpane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnArticleMouseClicked

    private void btnArticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseEntered
        // TODO add your handling code here:
        btnArticle.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnArticleMouseEntered

    private void btnArticleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseExited
        // TODO add your handling code here:
        btnArticle.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnArticleMouseExited

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(aboutpane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Keluar ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
            new main_awal().setVisible(true);
            this.dispose();
            break;
            case JOptionPane.NO_OPTION:
            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btn_pilihgambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihgambarActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(gambar_User.getWidth(), gambar_User.getHeight(), Image.SCALE_SMOOTH));
        gambar_User.setIcon(imageicon);
        lbl_path.setText(filename);
        
        try {
            File image =  new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new  ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            
            for(int readNum; (readNum = fis.read(buff)) !=-1;){
                bos.write(buff,0,readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "input gambar gagal "+e);
        }
    }//GEN-LAST:event_btn_pilihgambarActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update admin set "
                    +"kode=?, gambar=?"
                    +"where no =? ";
            PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tf_kodee.getText());
                ps.setBytes(2, person_image);
                ps.setString(3, tf_tampil.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil diUPDATE");
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "update gagal"+e);            
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void tf_jmlhBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jmlhBukuKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_jmlhBuku.getText().length()>=1) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Buku yang dipinjam terlalu banyak!!");
        }
    }//GEN-LAST:event_tf_jmlhBukuKeyTyped

    private void tf_tglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tglPinjamActionPerformed

    private void tf_ttlhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ttlhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ttlhariActionPerformed

    private void tglpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tglpinjamMouseClicked

    private void tglpinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseEntered
        // TODO add your handling code here:
        
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tglpinjamMouseEntered

    private void tglpinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseExited
        // TODO add your handling code here:
        
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tglpinjamMouseExited

    private void tglpinjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMousePressed

    private void tglpinjamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMouseReleased

    private void tglpinjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyPressed

    private void tglpinjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyReleased

    private void tglpinjamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyTyped

    private void tglkmblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglkmblMouseEntered
        // TODO add your handling code here:
        
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tglkmblMouseEntered

    private void btn_pilihgambar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihgambar1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_gambarbuku.getWidth(), lbl_gambarbuku.getHeight(), Image.SCALE_SMOOTH));
        lbl_gambarbuku.setIcon(imageicon);
        
        try {
            File image =  new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new  ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            
            for(int readNum; (readNum = fis.read(buff)) !=-1;){
                bos.write(buff,0,readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "input gambar "+e);
        }
    }//GEN-LAST:event_btn_pilihgambar1ActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String nama = tf_namaUser.getText();
        String idUser = tf_idUser.getText();
        String noBuku = lbl_nobuku.getText();
        String buku = tf_bukuuser.getText();
        String jmlhbuku = tf_jmlhBuku.getText();
        String pinjam = tf_tglPinjam.getText();
        String kembali = tf_tglkmbl.getText();
        String totalhari = tf_ttlhari.getText();
        //
        if (tf_idUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if(tf_namaUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_bukuuser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_jmlhBuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_tglkmbl.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_tglPinjam.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }
        
        else{
            try {
                String sql = "insert into pinjam (no_buku,id_user,nama,buku,jmlhbuku,tglPinjam,tglKmbl,totalHari) values (?,?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, noBuku);
                ps.setString(2, idUser);
                ps.setString(3, nama);
                ps.setString(4, buku);
                ps.setString(5, jmlhbuku);
                ps.setString(6, pinjam);
                ps.setString(7, kembali);
                ps.setString(8, totalhari);
                ps.executeUpdate();
                try {
                    String sql2 = "insert into history (no_buku,id_user,nama,buku,jmlhbuku,tglPinjam,tglKmbl,totalHari) values (?,?,?,?,?,?,?,?)";
                    PreparedStatement ps2 = conn.prepareStatement(sql2);
                    ps2.setString(1, noBuku);
                    ps2.setString(2, idUser);
                    ps2.setString(3, nama);
                    ps2.setString(4, buku);
                    ps2.setString(5, jmlhbuku);
                    ps2.setString(6, pinjam);
                    ps2.setString(7, kembali);
                    ps2.setString(8, totalhari);
                    ps2.executeUpdate();
                } catch (Exception e) {
                }
                
                bersih();
                JOptionPane.showMessageDialog(this, "berhasil menambahkan Data");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan "+e);
            }
        }

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_pinjamUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pinjamUbahActionPerformed
        // TODO add your handling code here:
        if (tf_idUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if(tf_namaUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_bukuuser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_jmlhBuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_tglkmbl.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_tglPinjam.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }
        
        else{
        try {
            String sql = "update pinjam set "
                    +"nama=?, buku=?, jmlhBuku=?, tglPinjam=?, tglKmbl=?, totalHari=?"
                    +"where no=?";
            PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tf_namaUser.getText());
                ps.setString(2, tf_bukuuser.getText());
                ps.setString(3, tf_jmlhBuku.getText());
                ps.setString(4, tf_tglPinjam.getText());
                ps.setString(5, tf_tglkmbl.getText());
                ps.setString (6, tf_ttlhari.getText());
                ps.setString(7, lbl_nopinjam.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Pinjam berhasil diUPDATE");
                bersih();
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Data Pinjam GAGAL"+e);

        }
    }//GEN-LAST:event_btn_pinjamUbahActionPerformed
    }
    private void btn_segarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_segarkanActionPerformed
        // 
        bersih();
    }//GEN-LAST:event_btn_segarkanActionPerformed

    private void btn_tambahbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahbukuActionPerformed
        // TODO add your handling code here:
        if (tf_namaBuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if(tf_penulis.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_stokbuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }
        else{
            try {
                String sql = "insert into buku (nama,penulis,stok,gambar) values (?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tf_namaBuku.getText());
                ps.setString(2, tf_penulis.getText());
                ps.setString(3, tf_stokbuku.getText());
                ps.setBytes(4, person_image);
                ps.executeUpdate();
               
                bersih();
                JOptionPane.showMessageDialog(this, "berhasil menambahkan Buku");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Buku Gagal ditambahkan "+e);
            }
        }
    }//GEN-LAST:event_btn_tambahbukuActionPerformed

    private void btn_ubahbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahbukuActionPerformed
        // TODO add your handling code here:
        if (tf_namaBuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if(tf_penulis.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }else if (tf_stokbuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "kolom kosong");
        }
        else{
        try {
            String sql = "update buku set "
                    +"nama=?, penulis=?, stok=?, gambar=? "
                    +"where no_buku=?";
            PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tf_namaBuku.getText());
                ps.setString(2, tf_penulis.getText());
                ps.setString(3, tf_stokbuku.getText());
                ps.setBytes(4, person_image);
                ps.setString(5, tf_idBuku.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Buku berhasil diUPDATE");
                bersih();
        } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Data Buku GAGAL"+ex);

        }
    }//GEN-LAST:event_btn_ubahbukuActionPerformed
    }
    private void btn_hapuspinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapuspinjamActionPerformed
        // TODO add your handling code here:
        if (tf_idUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "belum ada data yang dipilih!!!");
        }
        else{
        try {
           
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data Pinjam ini ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
                 JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                 String sql = "delete from pinjam where no ='"+lbl_nopinjam.getText()+"'" ;
                 PreparedStatement ps = conn.prepareStatement(sql);
                 ps.executeUpdate();
            //
                
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
                model.setRowCount(0);
                getDataPinjam();
                bersih();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapuspinjamActionPerformed
    }
    private void tabelPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPinjamMouseClicked
        // TODO add your handling code here:
        int baris = tabelPinjam.rowAtPoint(evt.getPoint());
        //
        String noPinjam = tabelPinjam.getValueAt(baris, 0).toString();
        String no_buku = tabelPinjam.getValueAt(baris, 1).toString();
        String id_user = tabelPinjam.getValueAt(baris, 2).toString();
        String nama = tabelPinjam.getValueAt(baris, 3).toString();
        String buku = tabelPinjam.getValueAt(baris, 4).toString();
        String dipinjam = tabelPinjam.getValueAt(baris, 5).toString();
        String tglPinjamm = tabelPinjam.getValueAt(baris, 6).toString();
        String tglKmbll = tabelPinjam.getValueAt(baris, 7).toString();
        String ttlhari = tabelPinjam.getValueAt(baris, 8).toString();


        lbl_nopinjam.setText(noPinjam);
        lbl_nobuku.setText(no_buku);
        tf_idUser.setText(id_user);
        tf_namaUser.setText(nama);
        tf_bukuuser.setText(buku);
        tf_jmlhBuku.setText(dipinjam);
        tf_tglPinjam.setText(tglPinjamm);
        tf_tglkmbl.setText(tglKmbll);
        tf_ttlhari.setText(ttlhari);
    }//GEN-LAST:event_tabelPinjamMouseClicked

    private void TabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelbukuMouseClicked
        // TODO add your handling code here:
        int row = Tabelbuku.getSelectedRow();
        TableModel model = Tabelbuku.getModel();
        //
        tf_idBuku.setText(model.getValueAt(row, 0).toString());
        tf_namaBuku.setText(model.getValueAt(row, 1).toString());
        tf_bukuuser.setText(model.getValueAt(row, 1).toString());
        tf_penulis.setText(model.getValueAt(row, 2).toString());
        tf_stokbuku.setText(model.getValueAt(row, 3).toString());


        //
        String tabel_click = (Tabelbuku.getModel().getValueAt(row, 0)).toString();
                         try {
                            String sql ="select gambar from buku where no_buku ='"+tabel_click+"'";
                            stat = conn.createStatement();
                            rs = stat.executeQuery(sql);
                                if (rs.next()) {
                                byte[] imagedata = rs.getBytes("gambar");
                                format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(lbl_gambarbuku.getWidth(), lbl_gambarbuku.getHeight(), Image.SCALE_SMOOTH));
                                lbl_gambarbuku.setIcon(format);
                                }
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, "Gambar tidak ada");  
                   int opsi = JOptionPane.showConfirmDialog(null, "mencari gambar ?");
                   switch(opsi){
                        case JOptionPane.YES_OPTION:    
                           JFileChooser chooser = new JFileChooser();
                                chooser.showOpenDialog(null);
                                File f = chooser.getSelectedFile();
                                filename = f.getAbsolutePath();
                                ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_gambarbuku.getWidth(), lbl_gambarbuku.getHeight(), Image.SCALE_SMOOTH));
                                lbl_gambarbuku.setIcon(imageicon);

                                try {
                                    File image =  new File(filename);
                                    FileInputStream fis = new FileInputStream(image);
                                    ByteArrayOutputStream bos = new  ByteArrayOutputStream();
                                    byte[] buff = new byte[1024];

                                    for(int readNum; (readNum = fis.read(buff)) !=-1;){
                                        bos.write(buff,0,readNum);
                                    }
                                    person_image = bos.toByteArray();
                                } catch (IOException ex) {
                                    JOptionPane.showMessageDialog(this, "input gambar "+ex);
                                }
                            break;
                        case JOptionPane.NO_OPTION:
                            break;
                        default:
                            break;
                           }
               }
    }//GEN-LAST:event_TabelbukuMouseClicked

    private void tglkmblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglkmblMouseExited
        // TODO add your handling code here:
        
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tglkmblMouseExited

    private void tfCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCariMouseClicked
        // TODO add your handling code here:
        tfCari.setText("");
                
    }//GEN-LAST:event_tfCariMouseClicked

    private void tfCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariKeyReleased
        // TODO add your handling code here:
        int jumlahrow = tabelAnggota.getRowCount();
        for(int n=0; n<jumlahrow; n++){
            model3.removeRow(0);
        }
        try {
        String sql ="select id,nama from registrasi where id like '%"+tfCari.getText()+"%'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        int no = 1;
        while (rs.next()) {
            Object[] o = new Object[2];
            o[0] = rs.getString("id");
            o[1] = rs.getString("nama");
            model3.addRow(o);
            no++;
        }
        tabelAnggota.setModel(model3);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cari eroor "+e);
    }
    }//GEN-LAST:event_tfCariKeyReleased

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        int row = tabelAnggota.getSelectedRow();
        TableModel model = tabelAnggota.getModel();
        //
        tf_idUser.setText(model.getValueAt(row, 0).toString());
        tf_namaUser.setText(model.getValueAt(row, 1).toString());
        
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
        // tglPINJAM
        String pilihtanggal = ((JTextField)tglpinjam.getDateEditor().getUiComponent()).getText();
        tf_tglPinjam.setText(pilihtanggal);
        // tglKEMBALI
        String pilihtgl = ((JTextField)tglkmbl.getDateEditor().getUiComponent()).getText();
        tf_tglkmbl.setText(pilihtgl);
        //totalHari
        try {
        SimpleDateFormat date = new SimpleDateFormat("MM dd, yyyy");
        String tanggal1 = String.valueOf(date.format(tglpinjam.getDate()));
        Date tangggalpinjam = (Date) date.parse(tanggal1);
        
        String tanggal2 = String.valueOf(date.format(tglkmbl.getDate()));
        Date tangggalkembali = (Date) date.parse(tanggal2);
        long total = Math.abs(tangggalkembali.getTime() - tangggalpinjam.getTime());
        //total
        tf_ttlhari.setText(""+ TimeUnit.MILLISECONDS.toDays(total));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel20MouseEntered

    private void cb_enabletfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_enabletfActionPerformed
        // TODO add your handling code here:
        if (cb_enabletf.isSelected()) {
            tf_idUser.setEnabled(true);
            tf_idUser.setEditable(true);
            tf_idBuku.setEditable(true);
            tf_idBuku.setEnabled(true);
            tf_bukuuser.setEditable(true);
            tf_bukuuser.setEnabled(true);
            tf_jmlhBuku.setEnabled(true);
            tf_jmlhBuku.setEditable(true);
            tf_ttlhari.setEditable(true);
            tf_ttlhari.setEnabled(true);

        }else{
            tf_idUser.setEnabled(false);
            tf_idUser.setEditable(false);
            tf_idBuku.setEnabled(false);
            tf_idBuku.setEditable(false);
            tf_bukuuser.setEditable(false);
            tf_bukuuser.setEditable(false);
            tf_jmlhBuku.setEditable(false);
            tf_jmlhBuku.setEditable(false);
            tf_ttlhari.setEditable(false);
            tf_ttlhari.setEditable(false);
        }
    }//GEN-LAST:event_cb_enabletfActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        // TODO add your handling code here:
        if (tf_idBuku.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "belum ada data yang dipilih!!!");
        }
        else{
        try {
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus Buku ini ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
                 JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                 String sql = "delete from buku where no_buku ='"+tf_idBuku.getText()+"'" ;
                 PreparedStatement ps = conn.prepareStatement(sql);
                 ps.executeUpdate();
            //
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
            model2.setRowCount(0);
            getDataBuku();
            bersih();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapus1ActionPerformed
    }
    private void btn_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus2ActionPerformed
        // TODO add your handling code here:
        if (tf_idUser.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "belum ada data yang dipilih!!!");
        }
        else{
        try {
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus Data ini ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
                 String sql = "delete from registrasi where id ='"+tf_idUser.getText()+"'" ;
                 PreparedStatement ps = conn.prepareStatement(sql);
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            //
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
            model3.setRowCount(0);
            getDataAnggota();
            bersih();
        } catch (HeadlessException | SQLException es) {
            JOptionPane.showMessageDialog(this, es);
        }
    }//GEN-LAST:event_btn_hapus2ActionPerformed
    }
    private void tf_idUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idUserKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_idUser.getText().length()>=12) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "karakter melebihi batas");
        }
    }//GEN-LAST:event_tf_idUserKeyTyped

    private void tf_stokbukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_stokbukuKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_stokbuku.getText().length()>=12) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "karakter melebihi batas");
        }
    }//GEN-LAST:event_tf_stokbukuKeyTyped

    private void cetak_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_pinjamActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String lokasifile = "C:\\Users\\USER\\Documents\\NetBeansProjects\\EduApps\\src\\reportEdu\\pinjam.jasper"; 
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(lokasifile);
            JasperPrint jprint = JasperFillManager.fillReport(lokasifile, null, conn);
            JasperViewer jview = new JasperViewer(jprint, false);
            jview.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jview.setVisible(true);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Report GAGAL karena "+e.getMessage());
        }
        
    }//GEN-LAST:event_cetak_pinjamActionPerformed

    private void bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String lokasifile = "C:\\Users\\USER\\Documents\\NetBeansProjects\\EduApps\\src\\reportEdu\\buku.jasper"; 
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(lokasifile);
            JasperPrint jprint = JasperFillManager.fillReport(lokasifile, null, conn);
            JasperViewer jview = new JasperViewer(jprint, false);
            jview.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jview.setVisible(true);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Report GAGAL karena "+e.getMessage());
        }
    }//GEN-LAST:event_bukuActionPerformed

    private void cetak_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_kembaliActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String lokasifile = "C:\\Users\\USER\\Documents\\NetBeansProjects\\EduApps\\src\\reportEdu\\kembali.jasper"; 
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(lokasifile);
            JasperPrint jprint = JasperFillManager.fillReport(lokasifile, null, conn);
            JasperViewer jview = new JasperViewer(jprint, false);
            jview.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jview.setVisible(true);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Report GAGAL karena "+e.getMessage());
        }
    }//GEN-LAST:event_cetak_kembaliActionPerformed

    private void anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String lokasifile = "C:\\Users\\USER\\Documents\\NetBeansProjects\\EduApps\\src\\reportEdu\\anggota.jasper"; 
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(lokasifile);
            JasperPrint jprint = JasperFillManager.fillReport(lokasifile, null, conn);
            JasperViewer jview = new JasperViewer(jprint, false);
            jview.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jview.setVisible(true);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Report GAGAL karena "+e.getMessage());
        }
    }//GEN-LAST:event_anggotaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        if (tf_cetakkembali.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Belum ada Data yang diPilih!!!");
        }else{
        try {
            String report = ("C:\\Users\\USER\\Documents\\"
                    +"NetBeansProjects\\EduApps\\src\\"
                    +"reportEdu\\reportkembali.jrxml");
            HashMap hash = new HashMap();
            hash.put("tkembali", tf_cetakkembali.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(report);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException Ejrpt) {
            System.out.println("report gagal karena "+Ejrpt);
        }
        
    }//GEN-LAST:event_kembaliActionPerformed
    }
    private void tabel_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pinjamMouseClicked
        // TODO add your handling code here:
        int baris = tabel_pinjam.rowAtPoint(evt.getPoint());
        //
        String pinjam = tabel_pinjam.getValueAt(baris, 2).toString();
        tf_cetakpinjam.setText(pinjam);
    }//GEN-LAST:event_tabel_pinjamMouseClicked

    private void tabel_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kembaliMouseClicked
        // TODO add your handling code here:
        int baris = tabel_kembali.rowAtPoint(evt.getPoint());
        //
        String kembali = tabel_kembali.getValueAt(baris, 2).toString();
        tf_cetakkembali.setText(kembali);
    }//GEN-LAST:event_tabel_kembaliMouseClicked

    private void pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamActionPerformed
        // TODO add your handling code here:
        if (tf_cetakpinjam.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Belum ada Data yang diPilih!!!");
        }else{
            try {
            String report = ("C:\\Users\\USER\\Documents\\"
                    +"NetBeansProjects\\EduApps\\src\\"
                    +"reportEdu\\pinjam_1.jrxml");
            HashMap hash = new HashMap();
            hash.put("pinjamparam", tf_cetakpinjam.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(report);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException Ejrpt) {
            System.out.println("report gagal karena "+Ejrpt);
        }
        }
        
    }//GEN-LAST:event_pinjamActionPerformed
public void warna(){
        lbl_nopinjam.setForeground(new Color(0,0,0,0));
        lbl_nobuku.setForeground(new Color(0,0,0,0));
        tf_id.setForeground(new Color(0,0,0,0));
        btnAbout.setForeground(new Color(0,0,0,0));
        btnProfile.setForeground(new Color(0,0,0,0));
        btnLibrary.setForeground(new Color(0,0,0,0));
        btnLogout.setForeground(new Color(0,0,0,0));
        btnArticle.setForeground(new Color(0,0,0,0));
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
        tf_cetakkembali.setBackground(new Color(0,0,0,0));
        tf_cetakkembali.setForeground(new Color(0,0,0,0));
        tf_cetakpinjam.setBackground(new Color(0,0,0,0));
        tf_cetakpinjam.setForeground(new Color(0,0,0,0));
//        tf_bukuuser.setBackground(new Color(0,0,0,0));
//        tf_id.setBackground(new Color(0,0,0,0));
//        tf_idBuku.setBackground(new Color(0,0,0,0));
//        tf_jmlhBuku.setBackground(new Color(0,0,0,0));
//        tf_kodee.setBackground(new Color(0,0,0,0));
//        tf_namaBuku.setBackground(new Color(0,0,0,0));
//        tf_namaUser.setBackground(new Color(0,0,0,0));
//        tf_penulis.setBackground(new Color(0,0,0,0));
//        tf_stokbuku.setBackground(new Color(0,0,0,0));
//        tf_tglPinjam.setBackground(new Color(0,0,0,0));
//        tf_tglkmbl.setBackground(new Color(0,0,0,0));
//        tf_tglkmbl.setBackground(new Color(0,0,0,0));
//        tf_ttlhari.setBackground(new Color(0,0,0,0));
//        tf_idUser.setBackground(new Color(0,0,0,0));
}
public void bersih(){
        lbl_nopinjam.setText("");
        tf_bukuuser.setText("");
        tf_id.setText("");
        tf_idBuku.setText("");
        tf_jmlhBuku.setText("");
        tf_kodee.setText("");
        tf_namaBuku.setText("");
        tf_namaUser.setText("");
        tf_penulis.setText("");
        tf_stokbuku.setText("");
        tf_tglPinjam.setText("");
        tf_tglkmbl.setText("");
        tf_tglkmbl.setText("");
        tf_ttlhari.setText("");
        tf_idUser.setText("");
        lbl_gambarbuku.setIcon(null);
        //
        
        model.setRowCount(0);
        getDataPinjam();
        model2.setRowCount(0);
        getDataBuku();
        model3.setRowCount(0);        
        getDataAnggota();
}
public void getDataPinjam(){
    try {
        String sql ="select*from pinjam";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] objk = new Object[9];
            objk [0] = rs.getString("no");
            objk [1] = rs.getString("no_buku");
            objk [2] = rs.getString("id_user");
            objk [3] = rs.getString("nama");
            objk [4] = rs.getString("buku");
            objk [5] = rs.getString("jmlhBuku");
            objk [6] = rs.getString("tglPinjam");
            objk [7] = rs.getString("tglKmbl");
            objk [8] = rs.getString("totalHari");
            model.addRow(objk);
        }
        } catch (SQLException e) {
            System.out.println("tabel pinjam salah = "+e);
        }
}
public void getDataBuku(){
    try {
        String sql ="select*from buku";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] obj = new Object[4];
            obj [0] = rs.getString("no_buku");
            obj [1] = rs.getString("nama");
            obj [2] = rs.getString("penulis");
            obj [3] = rs.getString("stok");
            model2.addRow(obj);
        }
        } catch (SQLException e) {
            System.out.println("tabel buku salah = "+e);
        }
}
public void getDataAnggota(){
    try {
        String sql ="select id,nama  from registrasi";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] obj = new Object[2];
            obj [0] = rs.getString("id");
            obj [1] = rs.getString("nama");
            model3.addRow(obj);
        }
        } catch (SQLException e) {
            System.out.println("tabel buku salah = "+e);
        }
}
public void getDataAnggota2(){
    try {
        String sql ="select id,nama,email,password from registrasi";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] obj = new Object[4];
            obj [0] = rs.getString("id");
            obj [1] = rs.getString("nama");
            obj [2] = rs.getString("email");
            obj [3] = rs.getString("password");

            model4.addRow(obj);
        }
        } catch (SQLException e) {
            System.out.println("tabel buku salah = "+e);
        }
}
public void getDataKembali(){
    try {
        String sql ="select*from kembali";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] objk = new Object[8];
            objk [0] = rs.getString("no");
            objk [1] = rs.getString("no_buku");
            objk [2] = rs.getString("id_user");
            objk [3] = rs.getString("nama");
            objk [4] = rs.getString("buku");
            objk [5] = rs.getString("jmlhBuku");
            objk [6] = rs.getString("tlgPinjam");
            objk [7] = rs.getString("tglKmbl");
            model5.addRow(objk);
        }
        } catch (SQLException e) {
            System.out.println("tabel kembali salah = "+e);
        }
}
public void tampilgambar(){
    try {
        String  sql ="select*from admin where kode='"+tf_id.getText()+"'";
        stat=conn.createStatement();
        rs=stat.executeQuery(sql);
        if (rs.next()) {
            tf_tampil.setText(rs.getString(4));
        }
    } catch (Exception e) {
    }
    try {
        String  sql="select gambar from admin where kode='"+tf_id.getText()+"'";
        stat=conn.createStatement();
        rs=stat.executeQuery(sql);
        if (rs.next()) {
           byte[] imagedata = rs.getBytes("gambar");
                format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(gambar_User.getWidth(), gambar_User.getHeight(), Image.SCALE_SMOOTH));
                gambar_User.setIcon(format);
                //
                tf_kodee.setText(tf_id.getText());
                        
        }
         
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"gagal menampilkan gambar"+ e);
    }
    
}


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPane;
    private javax.swing.JTable Tabelbuku;
    private javax.swing.JPanel aboutpane;
    private javax.swing.JButton anggota;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnArticle;
    private javax.swing.JLabel btnLibrary;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JButton btn_hapus1;
    private javax.swing.JButton btn_hapus2;
    private javax.swing.JButton btn_hapuspinjam;
    private javax.swing.JButton btn_pilihgambar;
    private javax.swing.JButton btn_pilihgambar1;
    private javax.swing.JButton btn_pinjamUbah;
    private javax.swing.JButton btn_segarkan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambahbuku;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btn_ubahbuku;
    private javax.swing.JButton buku;
    private javax.swing.JCheckBox cb_enabletf;
    private javax.swing.JButton cetak_kembali;
    private javax.swing.JButton cetak_pinjam;
    private javax.swing.JLabel gambar_User;
    private javax.swing.JLabel gambarprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel kananpane;
    private javax.swing.JButton kembali;
    private javax.swing.JPanel kiri;
    private javax.swing.JLabel lbl_gambarbuku;
    private javax.swing.JLabel lbl_nobuku;
    private javax.swing.JLabel lbl_nopinjam;
    private javax.swing.JLabel lbl_path;
    private javax.swing.JPanel librarypane;
    private javax.swing.JButton pinjam;
    private javax.swing.JPanel profilepane;
    private javax.swing.JPanel reportpane;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JTable tabelPinjam;
    private javax.swing.JTable tabel_anggota;
    private javax.swing.JTable tabel_buku;
    private javax.swing.JTable tabel_kembali;
    private javax.swing.JTable tabel_pinjam;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tf_bukuuser;
    private javax.swing.JTextField tf_cetakkembali;
    private javax.swing.JTextField tf_cetakpinjam;
    private javax.swing.JLabel tf_id;
    private javax.swing.JTextField tf_idBuku;
    private javax.swing.JTextField tf_idUser;
    private javax.swing.JTextField tf_jmlhBuku;
    private javax.swing.JTextField tf_kodee;
    private javax.swing.JTextField tf_namaBuku;
    private javax.swing.JTextField tf_namaUser;
    private javax.swing.JTextField tf_penulis;
    private javax.swing.JTextField tf_stokbuku;
    private javax.swing.JLabel tf_tampil;
    private javax.swing.JTextField tf_tglPinjam;
    private javax.swing.JTextField tf_tglkmbl;
    private javax.swing.JTextField tf_ttlhari;
    private com.toedter.calendar.JDateChooser tglkmbl;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables
}
