/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class MainUtama extends javax.swing.JFrame {

    private static Connection conn;
    private static Statement stat;
    private static ResultSet rs;
    private static DefaultTableModel model;
    private static DefaultTableModel model2;
    //
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;

    public MainUtama(String input) {
        initComponents();
        conn = Koneksi.koneksi();
        //parameter
        lbl_emailUser.setText(input);
        //menampilkan profile
        param();
        //warna
        warna();
        //tabelSiswa
        model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Penulis");
        model.addColumn("Stok");
    jTable1.setModel(model);
    getDataSiswa();
        //tabelrekap
        model2 = new DefaultTableModel();
        model2.addColumn("No");
        model2.addColumn("No Buku");
        model2.addColumn("ID User");
        model2.addColumn("Nama");
        model2.addColumn("Buku");
        model2.addColumn("Dpinjam");
        model2.addColumn("Tanggal Pinjam");
        model2.addColumn("Tanggal Kembali");
    tabelRekap.setModel(model2);
    getDataRekap();
    notEditabel();
    //
    tanggalHariIni();
    }

    MainUtama() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JPanel();
        kiripane = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        btnLibrary = new javax.swing.JLabel();
        btnArticle = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        gambarkiri = new javax.swing.JLabel();
        kananpane = new javax.swing.JPanel();
        gambarwelcome = new javax.swing.JLabel();
        profilepane = new javax.swing.JPanel();
        lbl_namaUser = new javax.swing.JLabel();
        lbl_emailUser = new javax.swing.JLabel();
        lbl_hpUser = new javax.swing.JLabel();
        pas_user = new javax.swing.JPasswordField();
        gambar_User = new javax.swing.JLabel();
        lbl_setting = new javax.swing.JLabel();
        gambarprofile = new javax.swing.JLabel();
        Librarypane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_cari = new javax.swing.JTextField();
        tf_idUser = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_buku = new javax.swing.JTextField();
        tf_jmlhBuku = new javax.swing.JTextField();
        tf_ttlhari = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        tf_tglPinjam = new javax.swing.JTextField();
        tglkmbl = new com.toedter.calendar.JDateChooser();
        lbl_click = new javax.swing.JLabel();
        tf_tglkmbl = new javax.swing.JTextField();
        btn_preview = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_pinjam = new javax.swing.JButton();
        lbl_nobuku = new javax.swing.JLabel();
        gambarLibrary = new javax.swing.JLabel();
        RekapPane = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        brn_pulih = new javax.swing.JButton();
        id_userpinjam = new javax.swing.JTextField();
        nama_pinjam = new javax.swing.JTextField();
        buku_pinjam = new javax.swing.JTextField();
        tf_pinjam = new javax.swing.JTextField();
        tgl_pinjam = new javax.swing.JTextField();
        tgl_kembali = new javax.swing.JTextField();
        btn_cetak1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRekap = new javax.swing.JTable();
        lbl_no_buku = new javax.swing.JLabel();
        lbl_no = new javax.swing.JLabel();
        gambarrekap = new javax.swing.JLabel();
        AboutPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPane.setBackground(new java.awt.Color(255, 255, 255));
        MainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kiripane.setBackground(new java.awt.Color(0, 0, 0));
        kiripane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(1, 193, 198));
        btnProfile.setText("I");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
        });
        kiripane.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 208, 223, 40));

        btnLibrary.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLibrary.setForeground(new java.awt.Color(1, 193, 198));
        btnLibrary.setText("I");
        btnLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibraryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibraryMouseExited(evt);
            }
        });
        kiripane.add(btnLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 272, 223, 40));

        btnArticle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnArticle.setForeground(new java.awt.Color(1, 193, 198));
        btnArticle.setText("I");
        btnArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticleMouseExited(evt);
            }
        });
        kiripane.add(btnArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 334, 223, 40));

        btnAbout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(1, 193, 198));
        btnAbout.setText("I");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        kiripane.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 398, 223, 40));

        btnLogout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(1, 193, 198));
        btnLogout.setText("I");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        kiripane.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 503, 223, 40));

        gambarkiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kiri2.jpg"))); // NOI18N
        kiripane.add(gambarkiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        MainPane.add(kiripane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        kananpane.setBackground(new java.awt.Color(255, 255, 255));
        kananpane.setLayout(new java.awt.CardLayout());

        gambarwelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Kanan.JPG"))); // NOI18N
        gambarwelcome.setText("jLabel2");
        kananpane.add(gambarwelcome, "card2");

        profilepane.setBackground(new java.awt.Color(255, 255, 255));
        profilepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_namaUser.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lbl_namaUser.setForeground(new java.awt.Color(89, 215, 201));
        lbl_namaUser.setText("-");
        profilepane.add(lbl_namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 405, 240, 30));

        lbl_emailUser.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lbl_emailUser.setForeground(new java.awt.Color(89, 215, 201));
        lbl_emailUser.setText("-");
        profilepane.add(lbl_emailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 405, 230, 30));

        lbl_hpUser.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lbl_hpUser.setForeground(new java.awt.Color(89, 215, 201));
        lbl_hpUser.setText("-");
        profilepane.add(lbl_hpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 465, 240, 30));

        pas_user.setForeground(new java.awt.Color(89, 215, 201));
        pas_user.setBorder(null);
        profilepane.add(pas_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 465, 230, 30));
        profilepane.add(gambar_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 170, 178, 156));

        lbl_setting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_setting.setForeground(new java.awt.Color(255, 255, 255));
        lbl_setting.setText("     .");
        lbl_setting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_setting.setVerifyInputWhenFocusTarget(false);
        lbl_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_settingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_settingMouseExited(evt);
            }
        });
        profilepane.add(lbl_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 189, 50, 58));

        gambarprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/profile2.jpg"))); // NOI18N
        profilepane.add(gambarprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kananpane.add(profilepane, "card3");

        Librarypane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Buku", "Nama", "Stok"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(31, 200, 199));
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Librarypane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 260, 310));

        tf_cari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_cari.setForeground(new java.awt.Color(255, 255, 255));
        tf_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_cari.setText("Cari Buku...");
        tf_cari.setToolTipText("");
        tf_cari.setBorder(null);
        tf_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cariMouseClicked(evt);
            }
        });
        tf_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_cariKeyReleased(evt);
            }
        });
        Librarypane.add(tf_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 260, 30));

        tf_idUser.setEditable(false);
        tf_idUser.setBackground(new java.awt.Color(255, 255, 255));
        tf_idUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_idUser.setForeground(new java.awt.Color(255, 255, 255));
        tf_idUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_idUser.setBorder(null);
        Librarypane.add(tf_idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 195, 100, 30));

        tf_nama.setEditable(false);
        tf_nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_nama.setForeground(new java.awt.Color(255, 255, 255));
        tf_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_nama.setBorder(null);
        Librarypane.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, 30));

        tf_buku.setEditable(false);
        tf_buku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_buku.setForeground(new java.awt.Color(255, 255, 255));
        tf_buku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_buku.setBorder(null);
        Librarypane.add(tf_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 230, 30));

        tf_jmlhBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_jmlhBuku.setForeground(new java.awt.Color(255, 255, 255));
        tf_jmlhBuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_jmlhBuku.setBorder(null);
        tf_jmlhBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jmlhBukuKeyTyped(evt);
            }
        });
        Librarypane.add(tf_jmlhBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 327, 100, 30));

        tf_ttlhari.setEditable(false);
        tf_ttlhari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_ttlhari.setForeground(new java.awt.Color(255, 255, 255));
        tf_ttlhari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_ttlhari.setBorder(null);
        tf_ttlhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ttlhariActionPerformed(evt);
            }
        });
        Librarypane.add(tf_ttlhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 465, 80, 30));

        tglpinjam.setBackground(new java.awt.Color(255, 255, 255));
        tglpinjam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglpinjam.setForeground(new java.awt.Color(255, 255, 255));
        tglpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tglpinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglpinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tglpinjamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tglpinjamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tglpinjamMouseReleased(evt);
            }
        });
        tglpinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tglpinjamKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tglpinjamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tglpinjamKeyTyped(evt);
            }
        });
        Librarypane.add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 375, 40, 30));

        tf_tglPinjam.setEditable(false);
        tf_tglPinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_tglPinjam.setForeground(new java.awt.Color(255, 255, 255));
        tf_tglPinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tglPinjam.setBorder(null);
        tf_tglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tglPinjamActionPerformed(evt);
            }
        });
        Librarypane.add(tf_tglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 374, 190, 30));

        tglkmbl.setBackground(new java.awt.Color(255, 255, 255));
        tglkmbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglkmbl.setForeground(new java.awt.Color(255, 255, 255));
        tglkmbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglkmblMouseEntered(evt);
            }
        });
        Librarypane.add(tglkmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 417, 40, 30));

        lbl_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_clickMouseEntered(evt);
            }
        });
        Librarypane.add(lbl_click, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 280, 60));

        tf_tglkmbl.setEditable(false);
        tf_tglkmbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_tglkmbl.setForeground(new java.awt.Color(255, 255, 255));
        tf_tglkmbl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tglkmbl.setBorder(null);
        Librarypane.add(tf_tglkmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 417, 190, 30));

        btn_preview.setBackground(new java.awt.Color(255, 255, 255));
        btn_preview.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_preview.setText("Preview");
        btn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previewActionPerformed(evt);
            }
        });
        Librarypane.add(btn_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 522, -1, -1));

        btn_refresh.setBackground(new java.awt.Color(255, 255, 255));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        Librarypane.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 522, -1, -1));

        btn_pinjam.setBackground(new java.awt.Color(255, 255, 255));
        btn_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_pinjam.setText("Pinjam");
        btn_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pinjamActionPerformed(evt);
            }
        });
        Librarypane.add(btn_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 522, -1, -1));

        lbl_nobuku.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nobuku.setText("No Buku");
        Librarypane.add(lbl_nobuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        gambarLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/library2.jpg"))); // NOI18N
        gambarLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gambarLibraryMouseEntered(evt);
            }
        });
        Librarypane.add(gambarLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kananpane.add(Librarypane, "card3");

        RekapPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cetak.setBackground(new java.awt.Color(255, 255, 255));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        RekapPane.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 484, 100, -1));

        brn_pulih.setBackground(new java.awt.Color(255, 255, 255));
        brn_pulih.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        brn_pulih.setText("Kembalikan");
        brn_pulih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_pulihActionPerformed(evt);
            }
        });
        RekapPane.add(brn_pulih, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 484, 100, -1));

        id_userpinjam.setEditable(false);
        id_userpinjam.setBackground(new java.awt.Color(255, 255, 255));
        id_userpinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id_userpinjam.setForeground(new java.awt.Color(255, 255, 255));
        id_userpinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        id_userpinjam.setBorder(null);
        RekapPane.add(id_userpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 200, 70, 30));

        nama_pinjam.setEditable(false);
        nama_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nama_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        nama_pinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nama_pinjam.setBorder(null);
        RekapPane.add(nama_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 246, 140, 30));

        buku_pinjam.setEditable(false);
        buku_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buku_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        buku_pinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        buku_pinjam.setBorder(null);
        RekapPane.add(buku_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 289, 140, 30));

        tf_pinjam.setEditable(false);
        tf_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        tf_pinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pinjam.setBorder(null);
        RekapPane.add(tf_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 330, 60, 30));

        tgl_pinjam.setEditable(false);
        tgl_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tgl_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        tgl_pinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tgl_pinjam.setBorder(null);
        tgl_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_pinjamActionPerformed(evt);
            }
        });
        RekapPane.add(tgl_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 380, 140, 30));

        tgl_kembali.setEditable(false);
        tgl_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tgl_kembali.setForeground(new java.awt.Color(255, 255, 255));
        tgl_kembali.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tgl_kembali.setBorder(null);
        RekapPane.add(tgl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 420, 140, 30));

        btn_cetak1.setBackground(new java.awt.Color(255, 255, 255));
        btn_cetak1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_cetak1.setText("Refresh");
        btn_cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak1ActionPerformed(evt);
            }
        });
        RekapPane.add(btn_cetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 484, 80, -1));

        tabelRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID User", "Buku", "Dipinjam"
            }
        ));
        tabelRekap.setFocusable(false);
        tabelRekap.setGridColor(new java.awt.Color(255, 255, 255));
        tabelRekap.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelRekap.setRowHeight(25);
        tabelRekap.setSelectionBackground(new java.awt.Color(31, 200, 199));
        tabelRekap.setShowVerticalLines(false);
        tabelRekap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRekapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRekap);

        RekapPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 430, 270));

        lbl_no_buku.setText("no_buku");
        RekapPane.add(lbl_no_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        lbl_no.setText("no");
        RekapPane.add(lbl_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        gambarrekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rekap3.jpg"))); // NOI18N
        RekapPane.add(gambarrekap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(RekapPane, "card5");

        AboutPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/About.jpg"))); // NOI18N
        AboutPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(AboutPane, "card6");

        MainPane.add(kananpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 0, 764, 600));

        getContentPane().add(MainPane, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(profilepane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(Librarypane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnLibraryMouseClicked

    private void btnArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(RekapPane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnArticleMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(AboutPane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Keluar ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:    
                new main_awal().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        // TODO add your handling code here:
        btnProfile.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        // TODO add your handling code here:
        btnProfile.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnProfileMouseExited

    private void btnLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseEntered
        // TODO add your handling code here:
        btnLibrary.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnLibraryMouseEntered

    private void btnLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseExited
        // TODO add your handling code here:
        btnLibrary.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnLibraryMouseExited

    private void btnArticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseEntered
        // TODO add your handling code here:
        btnArticle.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnArticleMouseEntered

    private void btnArticleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseExited
        // TODO add your handling code here:
       btnArticle.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnArticleMouseExited

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnAboutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnLogoutMouseExited

    private void tf_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cariMouseClicked
        // TODO add your handling code here:
        tf_cari.setText("");
    }//GEN-LAST:event_tf_cariMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        
          bersih();
          model.setRowCount(0);
          getDataSiswa();
         
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void tf_ttlhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ttlhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ttlhariActionPerformed

    private void btn_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pinjamActionPerformed
        // TODO add your handling code here:
        String nama = tf_nama.getText();
        String idUser = tf_idUser.getText();
        String noBuku = lbl_nobuku.getText();
        String buku = tf_buku.getText();
        String jmlhbuku = tf_jmlhBuku.getText();
        String pinjam = tf_tglPinjam.getText();
        String kembali = tf_tglkmbl.getText();
        String totalhari = tf_ttlhari.getText();
        //
        if (tf_nama.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom kosong");
                }else if(tf_buku.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }else if (tf_tglkmbl.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }
            else{
                try {
                    String sql = "insert into pinjam (no_buku,id_user,nama,buku,jmlhbuku,tglPinjam,tglKmbl,totalHari) values (?,?,?,?,?,?,?,?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, noBuku);
                    ps.setString(2, idUser);
                    ps.setString(3, nama);
                    ps.setString(4, buku);
                    ps.setString(5, jmlhbuku);
                    ps.setString(6, pinjam);
                    ps.setString(7, kembali);
                    ps.setString(8, totalhari);
                ps.executeUpdate();
                try {
                    String sql2 = "insert into history (no_buku,id_user,nama,buku,jmlhbuku,tglPinjam,tglKmbl,totalHari) values (?,?,?,?,?,?,?,?)";
                        PreparedStatement ps2 = conn.prepareStatement(sql2);
                        ps2.setString(1, noBuku);
                        ps2.setString(2, idUser);
                        ps2.setString(3, nama);
                        ps2.setString(4, buku);
                        ps2.setString(5, jmlhbuku);
                        ps2.setString(6, pinjam);
                        ps2.setString(7, kembali);
                        ps2.setString(8, totalhari);
                    ps2.executeUpdate();
            } catch (Exception e) {
            }
        model.setRowCount(0);
        getDataSiswa();
        model2.setRowCount(0);
        getDataRekap();
        bersih();
        JOptionPane.showMessageDialog(this, "berhasil menambahkan Data");
        } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan "+e);
        }
                }
        
    }//GEN-LAST:event_btn_pinjamActionPerformed

    private void tglkmblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglkmblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkmblMouseEntered

    private void tf_tglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tglPinjamActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String nobuku = jTable1.getValueAt(baris, 0).toString();
        String nama = jTable1.getValueAt(baris, 1).toString();
        tf_buku.setText(nama);
        lbl_nobuku.setText(nobuku);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previewActionPerformed
        // Preview Gambar
        String nobuku = lbl_nobuku.getText();
        new ReviewBuku(nobuku).setVisible(true);
        
    }//GEN-LAST:event_btn_previewActionPerformed

    private void tf_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cariKeyReleased
        // TODO add your handling code here:
        int jumlahrow = jTable1.getRowCount();
        for(int n=0; n<jumlahrow; n++){
            model.removeRow(0);
        }
        try {
        String sql ="select*from buku where nama like '%"+tf_cari.getText()+"%'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        int no = 1;
        while (rs.next()) {
            Object[] o = new Object[4];
            o[0] = rs.getString("no");
            o[1] = rs.getString("nama");
            o[2] = rs.getString("penulis");
            o[3] = rs.getString("stok");
            model.addRow(o);
            no++;
        }
        jTable1.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cari eroor "+e);
    }
    }//GEN-LAST:event_tf_cariKeyReleased

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
            String report = ("C:\\Users\\USER\\Documents\\"
                    +"NetBeansProjects\\EduApps\\src\\"
                    +"Main\\edureport.jrxml");
            HashMap hash = new HashMap();
            hash.put("pinjamReport", tf_idUser.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(report);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException Ejrpt) {
            System.out.println("report gagal karena "+Ejrpt);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void brn_pulihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_pulihActionPerformed
    // TODO add your handling code here:
        String nama = nama_pinjam.getText();
        String idUser = id_userpinjam.getText();
        String noBuku = lbl_no_buku.getText();
        String buku = buku_pinjam.getText();
        String jmlhbuku = tf_pinjam.getText();
        String pinjam = tgl_pinjam.getText();
        String kembali = tgl_kembali.getText();
        //
        
        
        if (tf_nama.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");
                }else if(id_userpinjam.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");            
                }else if (nama_pinjam.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");            
                }else if (buku_pinjam.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");            
            }
            else{
            try {
                String sql="insert into kembali(no_buku, id_user, nama, buku, jmlhBuku, tlgPinjam, tglKmbl) values(?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, noBuku);
                ps.setString(2, idUser);
                ps.setString(3, nama);
                ps.setString(4, buku);
                ps.setString(5, jmlhbuku);
                ps.setString(6, pinjam);
                ps.setString(7, kembali);
                ps.executeUpdate();
                try {
                    String sql2="delete from pinjam where no ='"+lbl_no.getText()+"'";
                    PreparedStatement ps2 = conn.prepareStatement(sql2);
                    ps2.executeUpdate();
                    model2.setRowCount(0);
                    getDataRekap();
                    bersihrekap();
                    model.setRowCount(0);
                    getDataSiswa();
                } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "gagal menghapus"+ex.getMessage());            
        }
        JOptionPane.showMessageDialog(this, "Berhasil mengembalikan Buku");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "gagal mengembalikan buku"+e.getMessage());            
        }
                }
        
        
    }//GEN-LAST:event_brn_pulihActionPerformed

    private void tgl_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_pinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_pinjamActionPerformed

    private void tabelRekapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRekapMouseClicked
        // TODO add your handling code here:
        int baris = tabelRekap.rowAtPoint(evt.getPoint());
        //
        String notabel = tabelRekap.getValueAt(baris, 0).toString();
        String no_buku = tabelRekap.getValueAt(baris, 1).toString();
        String id_user = tabelRekap.getValueAt(baris, 2).toString();
        String nama = tabelRekap.getValueAt(baris, 3).toString();
        String buku = tabelRekap.getValueAt(baris, 4).toString();
        String dipinjam = tabelRekap.getValueAt(baris, 5).toString();
        String tglPinjamm = tabelRekap.getValueAt(baris, 6).toString();
        String tglKmbll = tabelRekap.getValueAt(baris, 7).toString();


        id_userpinjam.setText(id_user);
        buku_pinjam.setText(buku);
        tf_pinjam.setText(dipinjam);
        nama_pinjam.setText(nama);
        tgl_pinjam.setText(tglPinjamm);
        tgl_kembali.setText(tglKmbll);
        lbl_no_buku.setText(no_buku);
        lbl_no.setText(notabel);
    }//GEN-LAST:event_tabelRekapMouseClicked

    private void gambarLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarLibraryMouseEntered
       
        
    }//GEN-LAST:event_gambarLibraryMouseEntered

    private void btn_cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak1ActionPerformed
        // TODO add your handling code here:
          model2.setRowCount(0);
          getDataRekap();
          bersihrekap();
    }//GEN-LAST:event_btn_cetak1ActionPerformed

    private void lbl_clickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickMouseEntered
        // TODO add your handling code here:
         // tglPINJAM
//        String pilihtanggal = ((JTextField)tglpinjam.getDateEditor().getUiComponent()).getText();
//        tf_tglPinjam.setText(pilihtanggal);
        // tglKEMBALI
        String pilihtgl = ((JTextField)tglkmbl.getDateEditor().getUiComponent()).getText();
        tf_tglkmbl.setText(pilihtgl);
        //totalHari
        try {
        SimpleDateFormat date = new SimpleDateFormat("MM dd, yyyy");
        String tanggal1 = String.valueOf(date.format(tglpinjam.getDate()));
        Date tangggalpinjam = (Date) date.parse(tanggal1);
        
        String tanggal2 = String.valueOf(date.format(tglkmbl.getDate()));
        Date tangggalkembali = (Date) date.parse(tanggal2);
        long total = Math.abs(tangggalkembali.getTime() - tangggalpinjam.getTime());
        //total
        tf_ttlhari.setText(""+ TimeUnit.MILLISECONDS.toDays(total));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_lbl_clickMouseEntered

    private void lbl_settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_settingMouseEntered
        // TODO add your handling code here:
        lbl_setting.setForeground(Color.white);
    }//GEN-LAST:event_lbl_settingMouseEntered

    private void lbl_settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_settingMouseExited
        // TODO add your handling code here:
        lbl_setting.setForeground(new Color(0,0,0,0));
    }//GEN-LAST:event_lbl_settingMouseExited

    private void lbl_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_settingMouseClicked
        // TODO add your handling code here:
        String iduser = tf_idUser.getText();
        new pengaturan(iduser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_settingMouseClicked

    private void tf_jmlhBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jmlhBukuKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_jmlhBuku.getText().length()>=1) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Buku yang dipinjam terlalu banyak!!");
        }
    }//GEN-LAST:event_tf_jmlhBukuKeyTyped

    private void tglpinjamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyTyped

    private void tglpinjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyReleased

    private void tglpinjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglpinjamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamKeyPressed

    private void tglpinjamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMouseReleased

    private void tglpinjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMousePressed

    private void tglpinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMouseExited

    private void tglpinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMouseEntered

    private void tglpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tglpinjamMouseClicked
    public void param(){
        String emailUser = lbl_emailUser.getText();
        try {
            String sql = "Select*from registrasi where email='"+emailUser+"'";
            stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            //
            while (rs.next()) {
                lbl_namaUser.setText(rs.getString(2));
                tf_nama.setText(rs.getString(2));
                pas_user.setText(rs.getString(3));
                lbl_hpUser.setText(rs.getString(4));
                tf_idUser.setText(rs.getString(6));
               
            }
                     try {
                            String sql2 ="select gambar from registrasi where email='"+emailUser+"'";
                            stat = conn.createStatement();
                            rs = stat.executeQuery(sql2);
                                if (rs.next()) {
                                byte[] imagedata = rs.getBytes("gambar");
                                format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(gambar_User.getWidth(), gambar_User.getHeight(), Image.SCALE_SMOOTH));
                                gambar_User.setIcon(format);
                                //
                   }
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, "GAGAL menampilkan Gambar "+e);                   
               }
        } catch (Exception e) {
        }
}
    public void warna(){
        //
        btnAbout.setForeground(new Color(0,0,0,0));
        btnProfile.setForeground(new Color(0,0,0,0));
        btnLibrary.setForeground(new Color(0,0,0,0));
        btnLogout.setForeground(new Color(0,0,0,0));
        btnArticle.setForeground(new Color(0,0,0,0));
        //
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
        tf_buku.setBackground(new Color(0,0,0,0));
        tf_cari.setBackground(new Color(0,0,0,0));
        tf_idUser.setBackground(new Color(0,0,0,0));
        tf_nama.setBackground(new Color(0,0,0,0));
        tf_ttlhari.setBackground(new Color(0,0,0,0));
        tf_jmlhBuku.setBackground(new Color(0,0,0,0));
        tf_tglPinjam.setBackground(new Color(0,0,0,0));
        tf_tglkmbl.setBackground(new Color(0,0,0,0));
        lbl_nobuku.setForeground(new Color(0,0,0,0));
        lbl_no.setForeground(new Color(0,0,0,0));
        lbl_no_buku.setForeground(new Color(0,0,0,0));

        //
        id_userpinjam.setBackground(new Color(0,0,0,0));
        nama_pinjam.setBackground(new Color(0,0,0,0));
        buku_pinjam.setBackground(new Color(0,0,0,0));
        tf_pinjam.setBackground(new Color(0,0,0,0));
        tgl_kembali.setBackground(new Color(0,0,0,0));
        tgl_pinjam.setBackground(new Color(0,0,0,0));
      
        //
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(255,255,255));
        jTable1.getTableHeader().setForeground(Color.BLACK);
        //
        lbl_setting.setForeground(new Color(0,0,0,0));
    
}
    public void bersih(){
        tf_buku.setText("");
        tf_jmlhBuku.setText("");
        tf_tglPinjam.setText("");
        tf_tglkmbl.setText("");
        tf_ttlhari.setText("");
    }
    public void bersihrekap(){
        id_userpinjam.setText("");
        nama_pinjam.setText("");
        buku_pinjam.setText("");
        tf_pinjam.setText("");
        tgl_pinjam.setText("");
        tgl_kembali.setText("");
    }
    public void getDataSiswa(){
        try {
        String sql ="select*from buku";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] obj = new Object[4];
            obj [0] = rs.getString("no_buku");
            obj [1] = rs.getString("nama");
            obj [2] = rs.getString("penulis");
            obj [3] = rs.getString("stok");
            model.addRow(obj);
        }
        } catch (Exception e) {
        }
    }
    public void notEditabel(){
    JTextField f = new JTextField();
        f.setEditable(false);
        for (int i = 0; i < tabelRekap.getColumnModel().getColumnCount(); i++) {
        tabelRekap.getColumnModel().getColumn(i).setCellEditor(new DefaultCellEditor(f));
        }for (int i = 0; i < jTable1.getColumnModel().getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellEditor(new DefaultCellEditor(f));
        }
    }
    public void getDataRekap(){
        try {
        String sql ="select*from pinjam where id_user='"+tf_idUser.getText()+"'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] objk = new Object[9];
            objk [0] = rs.getString("no");
            objk [1] = rs.getString("no_buku");
            objk [2] = rs.getString("id_user");
            objk [3] = rs.getString("nama");
            objk [4] = rs.getString("buku");
            objk [5] = rs.getString("jmlhBuku");
            objk [6] = rs.getString("tglPinjam");
            objk [7] = rs.getString("tglKmbl");
            objk [8] = rs.getString("totalHari");
            model2.addRow(objk);
        }
        } catch (SQLException e) {
            System.out.println("tabel rekap ada yg salah = "+e);
        }
    }
    public void tanggalHariIni(){
    Date ys = new Date();
    SimpleDateFormat s = new SimpleDateFormat("MM dd, yyyy");
    tf_tglPinjam.setText(s.format(ys));
    tglpinjam.setDate(ys);
}
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPane;
    private javax.swing.JPanel Librarypane;
    private javax.swing.JPanel MainPane;
    private javax.swing.JPanel RekapPane;
    private javax.swing.JButton brn_pulih;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnArticle;
    private javax.swing.JLabel btnLibrary;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_cetak1;
    private javax.swing.JButton btn_pinjam;
    private javax.swing.JButton btn_preview;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JTextField buku_pinjam;
    private javax.swing.JLabel gambarLibrary;
    private javax.swing.JLabel gambar_User;
    private javax.swing.JLabel gambarkiri;
    private javax.swing.JLabel gambarprofile;
    private javax.swing.JLabel gambarrekap;
    private javax.swing.JLabel gambarwelcome;
    private javax.swing.JTextField id_userpinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel kananpane;
    private javax.swing.JPanel kiripane;
    private javax.swing.JLabel lbl_click;
    private javax.swing.JLabel lbl_emailUser;
    private javax.swing.JLabel lbl_hpUser;
    private javax.swing.JLabel lbl_namaUser;
    private javax.swing.JLabel lbl_no;
    private javax.swing.JLabel lbl_no_buku;
    private javax.swing.JLabel lbl_nobuku;
    private javax.swing.JLabel lbl_setting;
    private javax.swing.JTextField nama_pinjam;
    private javax.swing.JPasswordField pas_user;
    private javax.swing.JPanel profilepane;
    private javax.swing.JTable tabelRekap;
    private javax.swing.JTextField tf_buku;
    private javax.swing.JTextField tf_cari;
    private javax.swing.JTextField tf_idUser;
    private javax.swing.JTextField tf_jmlhBuku;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_pinjam;
    private javax.swing.JTextField tf_tglPinjam;
    private javax.swing.JTextField tf_tglkmbl;
    private javax.swing.JTextField tf_ttlhari;
    private javax.swing.JTextField tgl_kembali;
    private javax.swing.JTextField tgl_pinjam;
    private com.toedter.calendar.JDateChooser tglkmbl;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables
}
