/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.stage.FileChooser;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class pengaturan extends javax.swing.JFrame {
    
    private Connection conn;
    private Statement stat;
    private ResultSet rs;
    
    
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    private FileChooser fileChooser;
    
    public pengaturan(String inputID) {
        initComponents();
        conn = Koneksi.koneksi();
        lbl_id.setText(inputID);
        //
        tampil();
        //
        path.setBackground(new Color(0,0,0,0));
        tf_fullname.setBackground(new Color(0,0,0,0));
        tf_hp.setBackground(new Color(0,0,0,0));
        tf_email.setBackground(new Color(0,0,0,0));
        tf_pass.setBackground(new Color(0,0,0,0));
        lbl_id.setForeground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_gambaruser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        tf_fullname = new javax.swing.JTextField();
        tf_hp = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbl_gambaruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 87, 178, 156));

        jButton1.setText("Update profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jButton2.setText("Pilih gambar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 100, -1));

        path.setEditable(false);
        path.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        path.setForeground(new java.awt.Color(255, 255, 255));
        path.setBorder(null);
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });
        jPanel1.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 190, 20));

        tf_fullname.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tf_fullname.setForeground(new java.awt.Color(255, 255, 255));
        tf_fullname.setBorder(null);
        jPanel1.add(tf_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 78, 160, 30));

        tf_hp.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tf_hp.setForeground(new java.awt.Color(255, 255, 255));
        tf_hp.setBorder(null);
        jPanel1.add(tf_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 160, 30));

        tf_email.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tf_email.setForeground(new java.awt.Color(255, 255, 255));
        tf_email.setBorder(null);
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        jPanel1.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 186, 160, 30));

        tf_pass.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tf_pass.setForeground(new java.awt.Color(255, 255, 255));
        tf_pass.setBorder(null);
        jPanel1.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 240, 160, 30));

        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("id");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        btn_back.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("<");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pengaturan.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        JFileChooser chooser = new JFileChooser();
        fileChooser = new FileChooser();
        fileChooser.getExtensionFilters().addAll(new FileChooser.ExtensionFilter("Image Files", "*.png","*.jpg","*jpeg","*.bmp"));
        //
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_gambaruser.getWidth(), lbl_gambaruser.getHeight(), Image.SCALE_SMOOTH));
        lbl_gambaruser.setIcon(imageicon);
        path.setText(filename);
        
        try {
            File image =  new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new  ByteArrayOutputStream();
            byte[] buff = new byte[40000000];
            
            for(int readNum; (readNum = fis.read(buff)) !=-1;){
                bos.write(buff,0,readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "input gambar "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email2 = tf_email.getText();
        String[] check = email2.split("@", 2);
        if (tf_email.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom kosong");
                }else if(tf_fullname.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }else if (tf_hp.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }else if (tf_pass.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");  
                    //
                }else if(tf_email.getText().length()<=10){
                    JOptionPane.showMessageDialog(this, "Karakter email terlalu pendek");
                }else if(tf_hp.getText().length()<=11){
                    JOptionPane.showMessageDialog(this, "no Hp terlalu pendek");
                }else if(tf_hp.getText().length()>=13){
                    JOptionPane.showMessageDialog(this, "no Hp terlalu panjang");
                }else if(tf_pass.getText().length()<6){
                    JOptionPane.showMessageDialog(this, "password terlalu pendek");   
                }else if(tf_fullname.getText().length()< 4){
                    JOptionPane.showMessageDialog(this, "nama terlalu pendek");   
                }else if (!"gmail.com".equals(String.valueOf(check[1]))) {
            JOptionPane.showMessageDialog(this, "Isi gmail woy!");
                }
            else{
                try {
            String sql = "update registrasi set "
                    +"email=?, nama=?, password=?, noHP=?, gambar=? "
                    +"where id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tf_email.getText());
                ps.setString(2, tf_fullname.getText());
                ps.setString(3, tf_pass.getText());
                ps.setString(4, tf_hp.getText()); 
                ps.setBytes(5, person_image);
                ps.setString(6, lbl_id.getText());
                ps.executeUpdate();
                bersih();
                JOptionPane.showMessageDialog(this, "Data berhasil diUPDATE");
                new Login().setVisible(true);
                this.dispose();
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "gagal diUPDATE"+e);

        }
             }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked
public void bersih(){
        path.setText("");
        tf_fullname.setText("");
        tf_hp.setText("");
        tf_email.setText("");
        tf_pass.setText("");
        lbl_gambaruser.setIcon(null);
}
public void tampil(){
    try {
        String sql = "select*from registrasi where id='"+lbl_id.getText()+"'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while (rs.next()) {
                tf_email.setText(rs.getString(1));
                tf_fullname.setText(rs.getString(2));
                tf_pass.setText(rs.getString(3));
                tf_hp.setText(rs.getString(4));
            }
        try {
                            String sql2 ="select gambar from registrasi where id='"+lbl_id.getText()+"'";
                            stat = conn.createStatement();
                            rs = stat.executeQuery(sql2);
                                if (rs.next()) {
                                byte[] imagedata = rs.getBytes("gambar");
                                format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(lbl_gambaruser.getWidth(), lbl_gambaruser.getHeight(), Image.SCALE_SMOOTH));
                                lbl_gambaruser.setIcon(format);
                                //
                   }
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, "GAGAL menampilkan Gambar "+e);                   
               }
    } catch (Exception e) {
    }
}
/**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_gambaruser;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTextField path;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fullname;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_pass;
    // End of variables declaration//GEN-END:variables
}
